# Generated by Django 2.2.5 on 2021-02-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='platform',
            field=models.CharField(blank=True, choices=[('C', 'Computer'), ('M', 'Mobile'), ('P', 'PlayStation'), ('X', 'XBox'), ('G', 'Global')], default='C', max_length=2, null=True),
        ),
    ]
