# Generated by Django 2.2.5 on 2021-02-24 00:59

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('country', models.CharField(blank=True, max_length=32, null=True)),
                ('show', models.BooleanField(blank=True, default=True, null=True)),
                ('game_type', models.CharField(blank=True, max_length=32, null=True)),
                ('type', models.CharField(blank=True, choices=[('K', 'Keys'), ('C', 'Charging')], default='K', max_length=2, null=True)),
                ('platform', models.CharField(blank=True, choices=[('C', 'Computer'), ('M', 'Mobile'), ('P', 'PlayStation'), ('X', 'XBox')], default='C', max_length=2, null=True)),
                ('notes', models.TextField(blank=True, default='', null=True)),
                ('about', models.TextField(blank=True, default='', null=True)),
                ('details', models.TextField(blank=True, default='', null=True)),
                ('video', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('facebook', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('website', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('youtube', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='games/logo')),
                ('bg_cover', models.ImageField(blank=True, null=True, upload_to='games/bg_cover')),
                ('bg_card', models.ImageField(blank=True, null=True, upload_to='games/bg_card')),
            ],
        ),
        migrations.CreateModel(
            name='GameCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('price', models.FloatField(blank=True, default=1, null=True)),
                ('discount', models.FloatField(blank=True, default=0.0, null=True)),
                ('max', models.IntegerField(blank=True, default=10, null=True)),
                ('min', models.IntegerField(blank=True, default=0, null=True)),
                ('points', models.IntegerField(blank=True, default=0, null=True)),
                ('sold_flag', models.IntegerField(blank=True, default=0, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_cards', to='app.Game')),
            ],
        ),
        migrations.DeleteModel(
            name='Platform',
        ),
        migrations.AlterField(
            model_name='enum',
            name='name',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='action',
            field=models.CharField(blank=True, choices=[('A', 'Add Balance'), ('R', 'Remove Balance'), ('S', 'Set Balance'), ('P', 'Pay')], default='A', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default=app.models.generate_user_name, max_length=64),
        ),
    ]
