# Generated by Django 2.2.5 on 2021-02-28 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210227_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='compete_order_date',
            new_name='compete_date',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_date',
            new_name='create',
        ),
        migrations.AddField(
            model_name='gamekey',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_keys', to='app.Order'),
        ),
        migrations.AddField(
            model_name='order',
            name='account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='extra_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
