# Generated by Django 2.2.5 on 2021-03-01 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210228_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='platform',
            field=models.CharField(blank=True, choices=[('C', 'C'), ('M', 'M'), ('P', 'P'), ('X', 'X'), ('G', 'G')], default='C', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='type',
            field=models.CharField(blank=True, choices=[('K', 'K'), ('C', 'C')], default='K', max_length=2, null=True),
        ),
    ]
