# Generated by Django 2.2.5 on 2021-03-02 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210302_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
