# Generated by Django 2.2.5 on 2021-03-08 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_order_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='review_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
