# Generated by Django 2.2.5 on 2021-03-12 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210309_0144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('price', models.FloatField(blank=True, default=1, null=True)),
                ('discount', models.FloatField(blank=True, default=0.0, null=True)),
                ('points', models.IntegerField(blank=True, default=0, null=True)),
                ('system_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('show', models.BooleanField(blank=True, default=True, null=True)),
                ('sold_flag', models.BooleanField(blank=True, default=False, null=True)),
                ('about', models.TextField(blank=True, default='', null=True)),
                ('details', models.TextField(blank=True, default='', null=True)),
                ('video', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='accessory/logo')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='accessory/images')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='accessory/images')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='accessory/images')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='accessory/images')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='accessory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='accessory_orders', to='app.Accessory'),
        ),
    ]
