# Generated by Django 2.2.5 on 2021-03-12 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210312_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessory',
            name='about',
        ),
    ]
