# Generated by Django 2.2.5 on 2021-03-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_accessory_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
