# Generated by Django 2.2.5 on 2021-03-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_accessory_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbedGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(blank=True, max_length=500, null=True)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('type', models.CharField(blank=True, max_length=32, null=True)),
                ('details', models.TextField(blank=True, default='', null=True)),
                ('video', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='embedGames/logo')),
            ],
        ),
    ]
