# Generated by Django 2.2.5 on 2021-03-12 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_embedgame'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='max',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AddField(
            model_name='accessory',
            name='min',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
