# Generated by Django 2.2.5 on 2021-03-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20210313_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='short_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
