# Generated by Django 2.2.5 on 2021-03-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_accessory_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ship_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
