# Generated by Django 2.2.5 on 2021-03-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_ads'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='ads',
            name='show',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
