# Generated by Django 2.2.5 on 2021-03-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20210314_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='error_msg',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='review_description',
            field=models.TextField(blank=True, max_length=555, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ship_location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
