# Generated by Django 2.2.5 on 2021-03-24 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_pointshop_money_reword'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cart',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
