# Generated by Django 2.2.5 on 2021-03-27 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20210324_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='hide_review',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='cart',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorite',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
    ]
