const PERMISSIONS = {
    MANAGE_USERS: '',
    MANAGE_ENUMS: '',
    MANAGE_INVOICE: '',
    MANAGE_GAMES: '',
    MANAGE_ORDERS: '',
    MANAGE_EMBED_GAMES: '',
    MANAGE_RESOURCES: '',
    MANAGE_ACCESSORIES: '',

    USER_HISTORY: ''
};

export default PERMISSIONS;